CustomerOrderProj/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomerOrderBusinessLayer;

namespace CustomerOrderProj.Controllers
{
    public class CustomerController : Controller
    {
        //Displaying Customer Index
        public ActionResult Index()
        {
            CustomerBusinessLayer customerBusinessLayer = new CustomerBusinessLayer();
            List<Customer> customers = customerBusinessLayer.Customers.ToList();

            return View(customers);
        }

        //HttpGet Method for adding new customer
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //HttpPost Method for adding new customer
        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                CustomerBusinessLayer customerBusinessLayer = new CustomerBusinessLayer();
                customerBusinessLayer.AddCustomer(customer);
                return RedirectToAction("Index");
            }
            return View();
        }
        
        //Edit method to update customer details
        [HttpGet]
        public ActionResult Edit(int id)
        {
            CustomerBusinessLayer customerBusinessLayer = new CustomerBusinessLayer();
            Customer customers = customerBusinessLayer.Customers.Single(cust => cust.CustomerID == id);
            return View(customers);
        }

        //Httppost Method for updating order
        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                CustomerBusinessLayer customerBusinessLayer = new CustomerBusinessLayer();
                customerBusinessLayer.UpdateCustomer(customer);
                return RedirectToAction("Index");
            }
            return View(customer);
        }

    }
}

CustomerOrderProj/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomerOrderProj.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

    }
}

CustomerOrderProj/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomerOrderBusinessLayer;


namespace CustomerOrderProj.Controllers
{
    public class OrderController : Controller
    {
        //Displaying Order Index
        public ActionResult Index()
        {
            OrderBusinessLayer orderBusinessLayer = new OrderBusinessLayer();
            List<Order> orders = orderBusinessLayer.Orders.ToList();
            
            return View(orders);
        }

        //HttpGet Method for creating new order
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //Httppost Method for creating new order
        [HttpPost]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                OrderBusinessLayer orderBusinessLayer = new OrderBusinessLayer();
                orderBusinessLayer.AddOrder(order);
                return RedirectToAction("Index");
            }
            return View();
        }

        //Edit method to update order details
        [HttpGet]
        public ActionResult Edit(int id)
        {
                OrderBusinessLayer orderBusinessLayer = new OrderBusinessLayer();
                Order orders = orderBusinessLayer.Orders.Single(or => or.OrderID == id);
                return View(orders);
        }

        //Httppost Method for updating order
        [HttpPost]
        public ActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                OrderBusinessLayer orderBusinessLayer = new OrderBusinessLayer();
                orderBusinessLayer.UpdateOrder(order);
                return RedirectToAction("Index");
            }
            return View(order);
        }
            

        //public ActionResult Details(int id)
        //{
        //    OrderContext orderContext = new OrderContext();
        //    Order orders = orderContext.orders.Single(or => or.OrderID == id);
        //    return View(orders);
        //}

    }
}

CustomerOrderProj/Views/Customer/Create.cshtml
@model CustomerOrderBusinessLayer.Customer

@{
    ViewBag.Title = "Create";
}

<div style="font-family:Verdana">

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Customer</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Gender)
        </div>
        <div class="editor-field">
            @Html.DropDownList("Gender", new List<SelectListItem> {
       new SelectListItem{ Text="Male", Value = "Male"},
          new SelectListItem{ Text="Female", Value = "Female"}
       },"Select Gender")
            @Html.ValidationMessageFor(model => model.Gender)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

    </div>


CustomerOrderProj/Views/Customer/Edit.cshtml
@model CustomerOrderBusinessLayer.Customer

@{
    ViewBag.Title = "Edit";
}

<div style="font-family:Verdana">

<h2>Update details of customer</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Customer</legend>

        @Html.HiddenFor(model => model.CustomerID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Gender)
        </div>
        <div class="editor-field">
            @Html.DropDownList("Gender", new List<SelectListItem> {
       new SelectListItem{ Text="Male", Value = "Male"},
          new SelectListItem{ Text="Female", Value = "Female"}
       },"Select Gender")
            @Html.ValidationMessageFor(model => model.Gender)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

</div>



CustomerOrderProj/Views/Customer/Index.cshtml
@model IEnumerable<CustomerOrderBusinessLayer.Customer>

@{
    ViewBag.Title = "Index";
}

<div style="font-family:Verdana">

<h2>Index</h2>

<p>
    @Html.ActionLink("Add New Customer", "Create")
</p>
<table border ="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CustomerID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CustomerID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CustomerID })
        </td>
    </tr>
}

</table>
    </div>

CustomerOrderProj/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div style="font-family:Verdana">
    <p>
    @Html.ActionLink("List of Customers", "Index", "Customer")
        </p>
    <p>
    @Html.ActionLink("List of Orders", "Index", "Order")
        </p>
    </div>

CustomerOrderProj/Views/Order/Create.cshtml
@model CustomerOrderBusinessLayer.Order

@{
    ViewBag.Title = "Create";
}

<div style="font-family:Verdana">

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Order</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderName)
            @Html.ValidationMessageFor(model => model.OrderName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomerID)
            @Html.ValidationMessageFor(model => model.CustomerID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

</div>

CustomerOrderProj/Views/Order/Details.cshtml
@model CustomerOrderProj.Models.Order

@{
    ViewBag.Title = "Order Details";
}

<div style="font-family:Arial">
<h2>Order Details</h2>
    <table>
        <tr>
            <td>
                <b>Order ID:</b>
            </td>
            <td>
                @Model.OrderID
            </td>
        </tr>
        <tr>
            <td>
                <b>Order Name:</b>
            </td>
            <td>
                @Model.OrderName
            </td>
        </tr><tr>
            <td>
                <b>Order Date:</b>
            </td>
            <td>
                @Model.Date
            </td>
        </tr><tr>
            <td>
                <b>Customer ID:</b>
            </td>
            <td>
                @Model.CustomerID
            </td>
        </tr>
    </table>
    @Html.ActionLink("Back to List", "Index", new {customerID = @Model.CustomerID})
    </div>

CustomerOrderProj/Views/Order/Edit.cshtml
@model CustomerOrderBusinessLayer.Order

@{
    ViewBag.Title = "Edit";
}

<div style="font-family:Verdana"
<h2>Update details of order</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Order</legend>

        @Html.HiddenFor(model => model.OrderID)

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderName)
            @Html.ValidationMessageFor(model => model.OrderName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomerID)
            @Html.ValidationMessageFor(model => model.CustomerID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

</div>

CustomerOrderProj/Views/Order/Index.cshtml
@model IEnumerable<CustomerOrderBusinessLayer.Order>

@{
    ViewBag.Title = "OrderList";
}

<div style="font-family:Verdana">

<h2>List of All Orders</h2>

<p>
    @Html.ActionLink("Add New Order", "Create")
</p>
<table border ="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerID)
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OrderID }) |
            @Html.ActionLink("Details", "Details", new { id=item.OrderID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OrderID })
        </td>
    </tr>
}

</table>
    </div>